name: Deploy Docker Image

on:
  push:
    branches: [ 'main' ]
    tags: [ 'v\d+.\d+.\d+.(stable|dev)\d+' ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}
  BUILD_TAG: ${{ github.ref_name/v// }}
  BUILD_TYPE: ${{ contains(github.ref_name, '.stable') && 'stable' || 'latest' }}

jobs:

  push_to_registry:

    runs-on: ubuntu-20.04

    steps:

      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Log in to registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            version=${{ env.BUILD_TAG }}
            branch=${{ env.BUILD_TYPE }}

          tags: |
            ${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_TAG }}
            ${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_TYPE }}
