name: Deploy Docker Image

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  push_to_registry:

    runs-on: ubuntu-20.04

    steps:

      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Log in to registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ github.actor }}/${{ env.IMAGE_NAME }}:latest
